# Generated by Django 6.0.4 on 2026-05-04 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='expenditure',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
            preserve_default=False,
        ),
    ]
