# Generated by Django 6.0.4 on 2026-05-04 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_core', '0002_sale_expenditure'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='capacity',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
