# Generated by Django 6.0.4 on 2026-04-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orm_core', '0002_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_type',
            field=models.CharField(choices=[('NE', 'Nepalese'), ('CH', 'Chinese'), ('IT', 'Italian'), ('GR', 'Greek'), ('OT', 'Other')], default='', max_length=2),
            preserve_default=False,
        ),
    ]
